server {

    listen 80;
    server_name notesApp.test;

    return 301 https://$host$request_uri;

}

server{

    listen 443 ssl;
    http2 on;
    server_name notesApp.test;

    ssl_certificate /etc/nginx/tls/notes.crt;
    ssl_certificate_key /etc/nginx/tls/notes.key;
    ssl_protocols TLSv1.2 TLSv1.3;


    access_log /var/log/nginx/notesApp-access.log;
    error_log  /var/log/nginx/notesApp-error.log;

    location / {
        proxy_pass http://127.0.0.1:8080;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 3s;
        proxy_read_timeout    10s;
    }
}
